#!/usr/bin/env bash
#
# setup_sahasraksha.sh
#
# Scaffolds the full SAHASRAKSHA repository: directory tree + stub files for
# both the FastAPI backend and the React Native frontend, per the SRS and
# docs/FILE_STRUCTURE.md / docs/context/ANTIGRAVITY_CONTEXT.md.
#
# Usage:
#   chmod +x setup_sahasraksha.sh
#   ./setup_sahasraksha.sh [target_dir]      # default target_dir: .
#
# Safe to re-run: existing files are never overwritten.

set -euo pipefail

ROOT="${1:-.}"

echo "Scaffolding SAHASRAKSHA into: $ROOT"

# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------

mkd() {
  mkdir -p "$ROOT/$1"
}

# write_stub <relative_path> <comment_prefix> <one-line note>
# Creates the file with a minimal header comment if it does not exist yet.
write_stub() {
  local rel="$1"
  local prefix="$2"
  local note="$3"
  local path="$ROOT/$rel"
  mkdir -p "$(dirname "$path")"
  if [ -f "$path" ]; then
    echo "  skip (exists): $rel"
    return
  fi
  {
    echo "${prefix} ${rel}"
    echo "${prefix} ${note}"
    echo "${prefix} Generated by setup_sahasraksha.sh — see docs/context/ANTIGRAVITY_CONTEXT.md"
  } > "$path"
  echo "  created: $rel"
}

write_py_init() {
  local rel="$1"
  local path="$ROOT/$rel"
  mkdir -p "$(dirname "$path")"
  [ -f "$path" ] && return
  printf '' > "$path"
}

# ---------------------------------------------------------------------------
# root-level files & dirs
# ---------------------------------------------------------------------------

mkd "docs/context"
mkd "docs/api-contracts"

if [ ! -f "$ROOT/README.md" ]; then
cat > "$ROOT/README.md" << 'EOF'
# SAHASRAKSHA

Intelligent Weather Station Health Monitoring — sensor-failure detection
platform for IMD Automatic Weather Stations across India.

This is NOT a weather forecasting application. See
`docs/context/ANTIGRAVITY_CONTEXT.md` for the full project context and
`docs/FILE_STRUCTURE.md` for the repository layout.

## Structure
- `backend/`  — FastAPI service (REST + WebSocket)
- `frontend/` — React Native app (TypeScript)
- `docs/`     — SRS-derived context and API contract notes

## Quick start (once services are implemented)
```
# backend
cd backend
python -m venv .venv && source .venv/bin/activate
pip install -r requirements.txt
uvicorn app.main:app --reload

# frontend
cd frontend
npm install
npm run start
```
EOF
echo "  created: README.md"
fi

if [ ! -f "$ROOT/.gitignore" ]; then
cat > "$ROOT/.gitignore" << 'EOF'
# python
__pycache__/
*.pyc
.venv/
*.egg-info/

# node
node_modules/
.expo/
dist/

# env
.env
.env.local

# os
.DS_Store
EOF
echo "  created: .gitignore"
fi

if [ ! -f "$ROOT/.env.example" ]; then
cat > "$ROOT/.env.example" << 'EOF'
# Shared root-level example. Backend and frontend also have their own
# .env.example files with service-specific variables.
ENVIRONMENT=development
EOF
echo "  created: .env.example"
fi

if [ ! -f "$ROOT/docker-compose.yml" ]; then
cat > "$ROOT/docker-compose.yml" << 'EOF'
version: "3.9"

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: sahasraksha
      POSTGRES_PASSWORD: sahasraksha
      POSTGRES_DB: sahasraksha
    ports:
      - "5432:5432"
    volumes:
      - sahasraksha_pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: unless-stopped
    env_file:
      - ./backend/.env.example
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  sahasraksha_pgdata:
EOF
echo "  created: docker-compose.yml"
fi

write_stub "docs/FILE_STRUCTURE.md" "<!--" "Copy the canonical tree from the project's FILE_STRUCTURE.md deliverable here. -->"
write_stub "docs/context/ANTIGRAVITY_CONTEXT.md" "<!--" "Copy the canonical ANTIGRAVITY_CONTEXT.md deliverable here before starting an IDE session. -->"
write_stub "docs/api-contracts/openapi-notes.md" "<!--" "Freeform notes on request/response shapes until FastAPI's generated OpenAPI schema is the source of truth. -->"

# ---------------------------------------------------------------------------
# BACKEND
# ---------------------------------------------------------------------------

echo "-- backend --"

mkd "backend/app/api/routes"
mkd "backend/app/schemas"
mkd "backend/app/services"
mkd "backend/app/models"
mkd "backend/app/db"
mkd "backend/app/core"
mkd "backend/app/websocket"
mkd "backend/tests"

for f in "backend/app/__init__" "backend/app/api/__init__" \
         "backend/app/api/routes/__init__" "backend/app/schemas/__init__" \
         "backend/app/services/__init__" "backend/app/models/__init__" \
         "backend/app/db/__init__" "backend/app/core/__init__" \
         "backend/app/websocket/__init__" "backend/tests/__init__"; do
  write_py_init "${f}.py"
done

write_stub "backend/app/main.py" "#" "FastAPI app entrypoint: CORS, routers, exception handlers, startup/shutdown DB hooks. SRS §17."

# api/routes
write_stub "backend/app/api/routes/health.py"      "#" "GET /api/v1/health — service + DB health check. SRS §18."
write_stub "backend/app/api/routes/network.py"     "#" "GET /api/v1/network/overview, /network/trend. SRS §8, §18."
write_stub "backend/app/api/routes/stations.py"    "#" "GET /api/v1/stations, /stations/map, /stations/{id}, /stations/{id}/readings, /stations/{id}/diagnosis. SRS §9-11, §18."
write_stub "backend/app/api/routes/alerts.py"      "#" "GET /api/v1/alerts (+ ?limit=3 for home). SRS §14, §18."
write_stub "backend/app/api/routes/heartbeat.py"   "#" "GET /api/v1/stations/{id}/heartbeat. Must return heartbeat_status=UNAVAILABLE when sampling is insufficient — never fabricate. SRS §13."
write_stub "backend/app/api/routes/maintenance.py" "#" "GET /api/v1/maintenance, work order creation. SRS §15, §18."
write_stub "backend/app/api/routes/live.py"        "#" "WS /api/v1/live — broadcasts reading + alert events. SRS §16, §22."
write_stub "backend/app/api/routes/analytics.py"   "#" "GET /api/v1/analytics — network/detection/failure-distribution/layer-contribution/throughput charts. SRS §24."
write_stub "backend/app/api/routes/demo.py"        "#" "Demo Mode fault-injection endpoints (spike/freeze/drift/step/noise/dropout/sluggish). SRS §25."

# schemas
write_stub "backend/app/schemas/station.py"     "#" "Pydantic models for the station health object (SRS §4)."
write_stub "backend/app/schemas/reading.py"     "#" "Pydantic models for raw + flagged readings (SRS §19)."
write_stub "backend/app/schemas/alert.py"       "#" "Pydantic models for alert payloads (SRS §14)."
write_stub "backend/app/schemas/heartbeat.py"   "#" "Pydantic models for heartbeat analysis responses, incl. UNAVAILABLE state (SRS §13)."
write_stub "backend/app/schemas/maintenance.py" "#" "Pydantic models for maintenance/work-order payloads (SRS §15)."
write_stub "backend/app/schemas/network.py"     "#" "Pydantic models for network overview/trend responses (SRS §8)."

# services
write_stub "backend/app/services/station_service.py"     "#" "Station CRUD/query logic, pagination, filtering, sorting (SRS §10)."
write_stub "backend/app/services/detection_service.py"   "#" "Pipeline aggregator: physics -> spatial -> heartbeat -> drift -> ML -> evidence -> health -> alert (SRS §20)."
write_stub "backend/app/services/physics_service.py"     "#" "Layer 1: rule-based physics validation, no ML. (SRS §2 Layer 1)."
write_stub "backend/app/services/spatial_service.py"     "#" "Layer 2: neighbour cross-check, spatial z-score, agreement. (SRS §2 Layer 2)."
write_stub "backend/app/services/heartbeat_service.py"   "#" "Layer 3: pressure heartbeat / solar-tide analysis. Must return UNAVAILABLE, never fabricate, on insufficient sampling. (SRS §2 Layer 3)."
write_stub "backend/app/services/drift_service.py"       "#" "Layer 4a: cumulative drift / CUSUM-style detection. (SRS §2 Layer 4)."
write_stub "backend/app/services/ml_service.py"          "#" "Layer 4b: ML tie-breaker for ambiguous cases only — must not override deterministic evidence. (SRS §2 Layer 4)."
write_stub "backend/app/services/alert_service.py"       "#" "Alert generation/lifecycle from detection results. (SRS §14, §20)."
write_stub "backend/app/services/maintenance_service.py" "#" "Maintenance prioritization + work order logic. (SRS §15)."

# models
write_stub "backend/app/models/station.py"   "#" "SQLAlchemy Station model. (SRS §23)."
write_stub "backend/app/models/reading.py"   "#" "SQLAlchemy Reading model, indexed on station_id + timestamp. (SRS §23)."
write_stub "backend/app/models/alert.py"     "#" "SQLAlchemy Alert model, indexed on status. (SRS §23)."
write_stub "backend/app/models/detection.py" "#" "SQLAlchemy Detection/evidence model. (SRS §23)."

# db
write_stub "backend/app/db/database.py"       "#" "SQLAlchemy engine/session setup, Postgres-ready, env-driven URL. (SRS §23)."
write_stub "backend/app/db/seed_mock_data.py" "#" "Generates realistic multi-station mock dataset; swappable for real IMD/NOAA ingestion later. (SRS §37)."

# core
write_stub "backend/app/core/config.py"     "#" "Pydantic Settings: env vars, CORS origins, API version prefix. (SRS §30)."
write_stub "backend/app/core/logging.py"    "#" "Structured logging setup. (SRS §30)."
write_stub "backend/app/core/exceptions.py" "#" "Centralized exception handlers registered on the FastAPI app. (SRS §30)."

# websocket
write_stub "backend/app/websocket/manager.py" "#" "Connection manager: broadcast reading/alert events, handle disconnects. (SRS §16, §22)."

# tests
write_stub "backend/tests/test_health.py"             "#" "Smoke test for GET /api/v1/health."
write_stub "backend/tests/test_stations.py"           "#" "Tests for station list/detail/map/pagination endpoints."
write_stub "backend/tests/test_detection_service.py"  "#" "Tests for full pipeline aggregation and evidence output shape."
write_stub "backend/tests/test_physics_service.py"    "#" "Tests for physics rule violations (e.g. dew point > temperature)."
write_stub "backend/tests/test_spatial_service.py"    "#" "Tests for spatial z-score / neighbour agreement calculations."
write_stub "backend/tests/test_heartbeat_service.py"  "#" "Tests incl. the UNAVAILABLE fallback on insufficient sampling."
write_stub "backend/tests/test_alerts.py"             "#" "Tests for alert generation and severity/status mapping."

if [ ! -f "$ROOT/backend/requirements.txt" ]; then
cat > "$ROOT/backend/requirements.txt" << 'EOF'
fastapi>=0.111
uvicorn[standard]>=0.29
pydantic>=2.7
pydantic-settings>=2.2
sqlalchemy>=2.0
websockets>=12.0
python-dotenv>=1.0
numpy>=1.26
pandas>=2.2
scikit-learn>=1.4
pytest>=8.0
httpx>=0.27
EOF
echo "  created: backend/requirements.txt"
fi

if [ ! -f "$ROOT/backend/Dockerfile" ]; then
cat > "$ROOT/backend/Dockerfile" << 'EOF'
FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
EOF
echo "  created: backend/Dockerfile"
fi

if [ ! -f "$ROOT/backend/.env.example" ]; then
cat > "$ROOT/backend/.env.example" << 'EOF'
ENVIRONMENT=development
DATABASE_URL=sqlite:///./sahasraksha.db
CORS_ORIGINS=http://localhost:19006,http://localhost:8081,http://localhost:3000,http://localhost:5173
API_V1_PREFIX=/api/v1
LOG_LEVEL=INFO
EOF
echo "  created: backend/.env.example"
fi

if [ ! -f "$ROOT/backend/pytest.ini" ]; then
cat > "$ROOT/backend/pytest.ini" << 'EOF'
[pytest]
testpaths = tests
EOF
echo "  created: backend/pytest.ini"
fi

# ---------------------------------------------------------------------------
# FRONTEND
# ---------------------------------------------------------------------------

echo "-- frontend --"

mkd "frontend/src/navigation"
mkd "frontend/src/screens/home"
mkd "frontend/src/screens/map"
mkd "frontend/src/screens/alerts"
mkd "frontend/src/screens/stations"
mkd "frontend/src/screens/diagnosis"
mkd "frontend/src/screens/heartbeat"
mkd "frontend/src/screens/maintenance"
mkd "frontend/src/screens/live"
mkd "frontend/src/screens/analytics"
mkd "frontend/src/screens/demo"
mkd "frontend/src/screens/edge"
mkd "frontend/src/screens/validation"
mkd "frontend/src/screens/settings"
mkd "frontend/src/components/common"
mkd "frontend/src/components/home"
mkd "frontend/src/components/stations"
mkd "frontend/src/components/alerts"
mkd "frontend/src/components/diagnosis"
mkd "frontend/src/components/maintenance"
mkd "frontend/src/components/live"
mkd "frontend/src/map"
mkd "frontend/src/charts"
mkd "frontend/src/services"
mkd "frontend/src/hooks"
mkd "frontend/src/store"
mkd "frontend/src/types"
mkd "frontend/src/theme"
mkd "frontend/src/utils"
mkd "frontend/src/assets/icons"
mkd "frontend/src/assets/images"

# navigation
write_stub "frontend/src/navigation/RootNavigator.tsx"       "//" "Top-level navigator wrapping the bottom tab navigator + modal/stack screens. (SRS §7)"
write_stub "frontend/src/navigation/BottomTabNavigator.tsx"  "//" "iOS-style floating/translucent tab bar: HOME, MAP, ALERTS, STATIONS. (SRS §7)"
write_stub "frontend/src/navigation/types.ts"                "//" "Navigation param list types."

# screens
write_stub "frontend/src/screens/home/HomeScreen.tsx"                   "//" "Network overview, hero health %, horizontal cards, hourly detection, 10-day trend, recent alerts. (SRS §8)"
write_stub "frontend/src/screens/map/MapScreen.tsx"                     "//" "India map, clustered/individual markers, layers, bottom sheet on tap. (SRS §9)"
write_stub "frontend/src/screens/alerts/AlertsScreen.tsx"               "//" "Critical / Monitoring / No Data alert sections. (SRS §14)"
write_stub "frontend/src/screens/stations/StationsScreen.tsx"           "//" "Searchable, filterable, sortable, paginated station list. (SRS §10)"
write_stub "frontend/src/screens/stations/StationDetailScreen.tsx"      "//" "Metric cards, neighbour agreement, sensor health matrix, why-flagged summary. (SRS §11)"
write_stub "frontend/src/screens/diagnosis/DiagnosisScreen.tsx"         "//" "Explainable-AI evidence cards (Physics/Spatial/Heartbeat/Drift-ML) + plain-English conclusion. (SRS §12)"
write_stub "frontend/src/screens/heartbeat/PressureHeartbeatScreen.tsx" "//" "Raw pressure vs heartbeat-strength chart, thresholds, sampling status. (SRS §13)"
write_stub "frontend/src/screens/maintenance/MaintenanceScreen.tsx"     "//" "Service Now / Monitor / Healthy grouped list + work order creation. (SRS §15)"
write_stub "frontend/src/screens/live/LiveDetectionScreen.tsx"          "//" "WebSocket live reading stream + throughput counter + reconnect UX. (SRS §16)"
write_stub "frontend/src/screens/analytics/AnalyticsScreen.tsx"         "//" "Network health, detection performance, failure distribution, layer contribution, throughput charts. (SRS §24)"
write_stub "frontend/src/screens/demo/DemoModeScreen.tsx"               "//" "SIH demo: simulate each of the 7 failure types, before/after/evidence/alert flow. (SRS §25)"
write_stub "frontend/src/screens/edge/EdgeAIScreen.tsx"                 "//" "ESP32 + BME280 edge architecture explainer + live sensor readings. (SRS §26)"
write_stub "frontend/src/screens/validation/ValidationScreen.tsx"       "//" "Dataset size, model comparison chart, calibration, holdout, throughput. (SRS §27)"
write_stub "frontend/src/screens/settings/SettingsScreen.tsx"           "//" "App settings (not detailed in SRS body — keep minimal)."

# components
write_stub "frontend/src/components/common/Card.tsx"           "//" "Base rounded/soft-shadow card used across all screens."
write_stub "frontend/src/components/common/SegmentedControl.tsx" "//" "iOS-style segmented control (used in Heartbeat screen etc.)."
write_stub "frontend/src/components/common/StatusBadge.tsx"    "//" "Renders HEALTHY/MONITOR/SERVICE_NOW/NO_DATA with correct color mapping. (SRS §4)"
write_stub "frontend/src/components/common/SkeletonLoader.tsx" "//" "Skeleton card/chart/list loading states. (SRS §29)"
write_stub "frontend/src/components/common/EmptyState.tsx"     "//" "Empty-state copy component (no alerts / no heartbeat data / no stations). (SRS §29)"
write_stub "frontend/src/components/common/ErrorState.tsx"     "//" "Error state with TRY AGAIN action. (SRS §29)"
write_stub "frontend/src/components/common/FloatingTabBar.tsx" "//" "Custom floating/translucent tab bar visual."
write_stub "frontend/src/components/common/BottomSheet.tsx"    "//" "Reusable iOS-style bottom sheet (used by Map station tap). (SRS §9)"
write_stub "frontend/src/components/home/HeroHealthCard.tsx"        "//" "Large hero % + network status header. (SRS §8)"
write_stub "frontend/src/components/home/HorizontalMetricCards.tsx" "//" "Network Health / Active Alerts / Pressure Heartbeat / Sensor Degradation / Reporting Health cards. (SRS §8)"
write_stub "frontend/src/components/home/HourlyDetectionRow.tsx"    "//" "Hourly readings-processed / anomalies-detected row. (SRS §8)"
write_stub "frontend/src/components/stations/StationListCard.tsx"   "//" "Single station row/card for the Stations list. (SRS §10)"
write_stub "frontend/src/components/stations/StationFilterChips.tsx" "//" "All/Healthy/Monitor/Service/No Data filter chips. (SRS §10)"
write_stub "frontend/src/components/alerts/AlertCard.tsx"           "//" "Alert card with evidence bullets + VIEW STATION action. (SRS §14)"
write_stub "frontend/src/components/diagnosis/EvidenceCard.tsx"     "//" "Single evidence card (Physics/Spatial/Heartbeat/Drift-ML). (SRS §12)"
write_stub "frontend/src/components/maintenance/WorkOrderCard.tsx"  "//" "Maintenance list card + CREATE WORK ORDER action. (SRS §15)"
write_stub "frontend/src/components/live/LiveReadingRow.tsx"        "//" "Single live-stream reading row. (SRS §16)"

# map
write_stub "frontend/src/map/StationMapView.tsx"       "//" "Map container: clustering, layers, current location. (SRS §9)"
write_stub "frontend/src/map/StationMarker.tsx"        "//" "Individual station marker colored by status."
write_stub "frontend/src/map/StationClusterMarker.tsx" "//" "Cluster marker shown when zoomed out."
write_stub "frontend/src/map/MapLayerControls.tsx"     "//" "Health/Temperature/Pressure/Reporting layer toggle."

# charts
write_stub "frontend/src/charts/LineTrendChart.tsx"           "//" "Reusable line chart (10-day network health, analytics trends)."
write_stub "frontend/src/charts/HeartbeatChart.tsx"           "//" "Heartbeat-strength chart with normal/monitor/alarm thresholds. (SRS §13)"
write_stub "frontend/src/charts/FailureDistributionChart.tsx" "//" "Station failure-type distribution chart. (SRS §24)"
write_stub "frontend/src/charts/LayerContributionChart.tsx"   "//" "Detection-layer contribution chart. (SRS §24)"

# services
write_stub "frontend/src/services/api.ts"             "//" "Base HTTP client (fetch/axios wrapper), API_V1_PREFIX, error normalization. (SRS §31)"
write_stub "frontend/src/services/stationApi.ts"      "//" "Station list/detail/map/readings/diagnosis calls."
write_stub "frontend/src/services/alertApi.ts"        "//" "Alerts calls."
write_stub "frontend/src/services/heartbeatApi.ts"    "//" "Heartbeat calls."
write_stub "frontend/src/services/networkApi.ts"      "//" "Network overview/trend calls."
write_stub "frontend/src/services/maintenanceApi.ts"  "//" "Maintenance + work order calls."
write_stub "frontend/src/services/analyticsApi.ts"    "//" "Analytics calls."
write_stub "frontend/src/services/demoApi.ts"         "//" "Demo Mode fault-injection calls."
write_stub "frontend/src/services/websocket.ts"       "//" "WebSocket client for /api/v1/live with reconnect handling. (SRS §16, §31)"

# hooks
write_stub "frontend/src/hooks/useNetworkOverview.ts" "//" "Fetch + cache network overview/trend."
write_stub "frontend/src/hooks/useStations.ts"        "//" "Paginated station list state."
write_stub "frontend/src/hooks/useStationDetail.ts"   "//" "Single station detail + diagnosis state."
write_stub "frontend/src/hooks/useAlerts.ts"          "//" "Alerts state."
write_stub "frontend/src/hooks/useHeartbeat.ts"       "//" "Heartbeat data + UNAVAILABLE handling."
write_stub "frontend/src/hooks/useLiveDetection.ts"   "//" "WebSocket subscription + throughput counter."
write_stub "frontend/src/hooks/useMaintenance.ts"     "//" "Maintenance list + work order actions."

# store
write_stub "frontend/src/store/index.ts"        "//" "Store root/provider setup."
write_stub "frontend/src/store/networkSlice.ts"  "//" "Network overview/trend slice."
write_stub "frontend/src/store/stationsSlice.ts" "//" "Stations list/detail slice."
write_stub "frontend/src/store/alertsSlice.ts"   "//" "Alerts slice."
write_stub "frontend/src/store/liveSlice.ts"     "//" "Live WebSocket stream slice."

# types
write_stub "frontend/src/types/station.ts"     "//" "Station + status enum types, mirrors backend schemas/station.py."
write_stub "frontend/src/types/reading.ts"     "//" "Reading types, mirrors backend schemas/reading.py."
write_stub "frontend/src/types/alert.ts"       "//" "Alert types, mirrors backend schemas/alert.py."
write_stub "frontend/src/types/heartbeat.ts"   "//" "Heartbeat types incl. UNAVAILABLE state, mirrors backend schemas/heartbeat.py."
write_stub "frontend/src/types/maintenance.ts" "//" "Maintenance/work-order types, mirrors backend schemas/maintenance.py."

# theme
write_stub "frontend/src/theme/colors.ts"     "//" "Sky-blue/white/pale-cyan/indigo/lavender palette + status color mapping. (SRS §6, §4)"
write_stub "frontend/src/theme/typography.ts" "//" "SF Pro-style type scale, large hero numbers."
write_stub "frontend/src/theme/spacing.ts"    "//" "Spacing scale for the spacious/premium layout."
write_stub "frontend/src/theme/index.ts"      "//" "Theme barrel export."

# utils
write_stub "frontend/src/utils/formatters.ts"  "//" "Date/number/percentage formatters."
write_stub "frontend/src/utils/statusColor.ts" "//" "Single source of truth mapping status enum -> color (SRS §4, §35)."
write_stub "frontend/src/utils/constants.ts"   "//" "Shared constants (API base URL fallback, thresholds display labels, etc.)."

# root frontend files
write_stub "frontend/App.tsx"  "//" "App root: theme provider, store provider, RootNavigator."
write_stub "frontend/index.js" "//" "Expo/RN entrypoint registering App.tsx."

if [ ! -f "$ROOT/frontend/package.json" ]; then
cat > "$ROOT/frontend/package.json" << 'EOF'
{
  "name": "sahasraksha-frontend",
  "version": "0.1.0",
  "private": true,
  "main": "index.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "test": "jest",
    "lint": "eslint src --ext .ts,.tsx"
  },
  "dependencies": {
    "react": "18.2.0",
    "react-native": "0.74.0",
    "@react-navigation/native": "^6.1.0",
    "@react-navigation/bottom-tabs": "^6.5.0",
    "@react-navigation/native-stack": "^6.9.0"
  },
  "devDependencies": {
    "typescript": "^5.4.0",
    "@types/react": "^18.2.0",
    "eslint": "^8.57.0"
  }
}
EOF
echo "  created: frontend/package.json"
fi

if [ ! -f "$ROOT/frontend/tsconfig.json" ]; then
cat > "$ROOT/frontend/tsconfig.json" << 'EOF'
{
  "extends": "expo/tsconfig.base",
  "compilerOptions": {
    "strict": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["src/*"]
    }
  }
}
EOF
echo "  created: frontend/tsconfig.json"
fi

write_stub "frontend/babel.config.js" "//" "Babel config for Expo/RN + module-resolver for @/ alias."
write_stub "frontend/metro.config.js" "//" "Metro bundler config."
write_stub "frontend/app.json"        "//" "Expo app manifest (name, slug, icons, splash)."

if [ ! -f "$ROOT/frontend/.env.example" ]; then
cat > "$ROOT/frontend/.env.example" << 'EOF'
API_BASE_URL=http://localhost:8000/api/v1
WS_BASE_URL=ws://localhost:8000/api/v1/live
EOF
echo "  created: frontend/.env.example"
fi

echo ""
echo "Done. Scaffolding complete."
