import React from 'react';
import { View, Text, ScrollView, StyleSheet } from 'react-native';
import { Card } from '../../components/common/Card';
import { Colors, Typography, Spacing } from '../../theme';

/**
 * Edge Deployment
 *
 * Every specification on this screen is taken from the actual compiled
 * firmware. The C source is generated by the notebook and compiles to the
 * sizes stated below. Capabilities that are not implemented, or not
 * validated, are listed explicitly rather than omitted.
 */
export const EdgeAIScreen: React.FC = () => {
  // Measured from the compiled artifact, not estimated.
  const specs: [string, string][] = [
    ['Target', 'ESP32 (generic dev board)'],
    ['Sensor bus', 'BME280 or BMP280 over I2C'],
    ['Channels', 'Temperature, Pressure, Humidity'],
    ['Firmware size', '1,885 bytes compiled (0.045% of flash)'],
    ['Runtime state', '~180 bytes per station'],
    ['Language', 'C, no dependencies beyond math.h'],
    ['Model coefficients', '33 floats, fixed at compile time'],
  ];

  // The bitmask the firmware actually returns from sg_update().
  const flags: [string, string][] = [
    ['0x01', 'Range violation -- value outside physical bounds'],
    ['0x02', 'Step violation -- implausible jump from previous reading'],
    ['0x04', 'Frozen -- identical value repeated past the run-length limit'],
    ['0x08', 'CUSUM drift -- accumulated one-way bias'],
    ['0x10', 'Tide degradation -- S2 pressure amplitude collapsed'],
  ];

  return (
    <ScrollView style={styles.screen} contentContainerStyle={styles.content}>
      <View style={styles.header}>
        <Text style={styles.subtitle}>HARDWARE DEPLOYMENT</Text>
        <Text style={styles.title}>Edge Micro-Sentinel</Text>
      </View>

      <Card style={styles.card} variant="highlight">
        <Text style={styles.cardHeading}>WHY EDGE AT ALL</Text>
        <Text style={styles.cardBody}>
          In remote Indian terrain -- the Western Ghats, Ladakh, the Thar --
          cellular telemetry is intermittent, and a station that cannot reach a
          server cannot be monitored by one. The same detection logic that runs
          in our cloud pipeline compiles to a standalone C firmware that runs on
          the sensor node itself, with no network connection of any kind.
        </Text>
      </Card>

      <Card style={styles.specCard}>
        <Text style={styles.specTitle}>MEASURED FIRMWARE SPECIFICATIONS</Text>
        {specs.map(([label, value], idx) => (
          <View key={idx} style={styles.specRow}>
            <Text style={styles.specLabel}>{label}</Text>
            <Text style={styles.specVal}>{value}</Text>
          </View>
        ))}
      </Card>

      <Card style={styles.card}>
        <Text style={styles.cardHeading}>1,885 BYTES, IN CONTEXT</Text>
        <Text style={styles.cardBody}>
          The entire detection stack -- physics gates, harmonic climatology,
          CUSUM drift accumulation and the S2 tide heartbeat -- fits in under two
          kilobytes. That is roughly one twenty-two-hundredth of the flash on a
          standard ESP32, leaving the rest of the chip for the application. The
          33 harmonic coefficients are baked in at compile time, so no model file
          is loaded and no fitting happens on device.
        </Text>
      </Card>

      <Card style={styles.specCard}>
        <Text style={styles.specTitle}>FAULT BITMASK RETURNED ON DEVICE</Text>
        <Text style={styles.flagIntro}>
          sg_update() returns a single byte. Each bit is one fault family,
          decided locally -- no server round trip.
        </Text>
        {flags.map(([bit, meaning], idx) => (
          <View key={idx} style={styles.specRow}>
            <Text style={styles.bitLabel}>{bit}</Text>
            <Text style={styles.specVal}>{meaning}</Text>
          </View>
        ))}
      </Card>

      <Card style={styles.card}>
        <Text style={styles.cardHeading}>WHAT THE EDGE BUILD DOES NOT DO</Text>
        <Text style={styles.cardBody}>
          The spatial-consistency layer needs neighbouring stations and therefore
          cannot run on an isolated node. The Isolation Forest layer is not
          compiled to the device. Wind, solar radiation and soil moisture are
          outside the validated channel set entirely. The tide-heartbeat layer
          requires roughly two weeks of local history before it produces a
          meaningful amplitude baseline, and reports nothing until it does.
        </Text>
      </Card>

      <View style={styles.footer}>
        <Text style={styles.footerText}>
          The C source is generated directly by the public notebook and compiles
          with no modification. Sizes above are read from the compiled object,
          not estimated.
        </Text>
      </View>
    </ScrollView>
  );
};

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  content: {
    padding: Spacing.md,
    paddingBottom: 100,
  },
  header: {
    marginBottom: Spacing.md,
  },
  subtitle: {
    ...Typography.small,
    color: Colors.paleCyan,
    letterSpacing: 0.8,
  },
  title: {
    ...Typography.title1,
    color: Colors.textPrimary,
  },
  card: {
    padding: Spacing.md,
    borderRadius: Spacing.radiusMd,
    marginBottom: Spacing.md,
  },
  cardHeading: {
    ...Typography.small,
    color: Colors.primary,
    fontWeight: '700',
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  cardBody: {
    ...Typography.caption,
    color: Colors.textSecondary,
    lineHeight: 20,
  },
  specCard: {
    padding: Spacing.md,
    borderRadius: Spacing.radiusMd,
    marginBottom: Spacing.md,
  },
  specTitle: {
    ...Typography.small,
    color: Colors.paleCyan,
    letterSpacing: 0.8,
    marginBottom: Spacing.sm,
  },
  specRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: Colors.borderSubtle,
  },
  specLabel: {
    ...Typography.captionBold,
    color: Colors.textPrimary,
    maxWidth: '42%',
  },
  specVal: {
    ...Typography.caption,
    color: Colors.textSecondary,
    maxWidth: '55%',
    textAlign: 'right',
  },
  bitLabel: {
    ...Typography.captionBold,
    color: Colors.primary,
    maxWidth: '20%',
  },
  flagIntro: {
    ...Typography.small,
    color: Colors.textMuted,
    lineHeight: 16,
    marginBottom: Spacing.sm,
  },
  footer: {
    marginTop: Spacing.xs,
    paddingTop: Spacing.md,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
  },
  footerText: {
    ...Typography.small,
    color: Colors.textMuted,
    lineHeight: 16,
  },
});
